Algoritmo "soma_vetor"


Var
    n, i : inteiro
    vet : vetor [0..09] de real
    soma, media : real

Inicio
    escreva("Quantos numeros voce vai digitar? ")
    leia(n)
    
    para i de 1 ate n faca
        escreva("Digite um numero: ")
        leia(vet[i])
    fimpara
    
    escreva("VALORES = ", vet[i])

    para vet[i] de 0 10 faca
        soma <-
    fimpara


Fimalgoritmo